meta_product_name: "Discounts-Discovery"
meta_title: "Find Discount"
meta_description: "Looking for discounts?  Discount-Discovery app gives you access to all nearby stores having sales and discounts on their products"
meta_image: "facebook.png" # should exist in `app/assets/images/`
